
#: set name ""

<LoginScreen>:
	orientation: "vertical"
	md_bg_color: (1, 0.5, 0.5, 1)
	spacing: "10dp"
	padding: ["45dp", "180dp", "45dp", "180dp"]

	MDTextField:
		id: entry
		multiline: False
		hint_text: "Enter Your Name"
		mode: "rectangle"

		line_color_normal: (0, 0, 0, 1)
		text_color_focus: (0, 0, 0, 1)
		line_color_focus: app.theme_cls.bg_light

		pos_hint: {"center_x": 0.5}

	MDLabel:
		id: display_name
		size_hint: 1, 0.2
		halign: "center"