
#: set name ""

<LoginScreen>:
    MDScreen:
        md_bg_color: self.theme_cls.secondaryContainerColor

        Image:
            source: "assets/logo.png"
            size_hint_x: 0.5
            allow_stretch: True
            pos_hint: {'center_x': 0.50,'center_y': 0.78}  


        MDLabel:
            
            text: "Monja Uploader"
            font_name: 'BPoppins'
            font_size: "50sp"

